import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { ThemeProvider } from 'next-themes'


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export const currentTheme = "system" //Optionally you can use dark or system as default theme...


export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme={currentTheme}
          enableSystem
          disableTransitionOnChange
        >

          <main>{children}</main>
        </ThemeProvider>
      </body>
    </html>
  );
}
